yatube/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('group/<slug:slug>/',
         views.group_list, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        max_length=200,
        blank=True,
        null=True,
        related_name='posts'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[0:15]

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from posts.models import Post, Group


def index(request):
    template = 'posts/index.html'
    title = 'Последние обновления на сайте'
    posts = Post.objects.all()[:10]
    context = {
        'title': title,
        'posts': posts}

    return render(request, template, context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    title = f'Записи сообщества {slug}'
    posts = group.posts.all()[:10]
    template = 'posts/group_list.html'
    context = {
        'title': title,
        'group': group,
        'posts': posts}
    return render(request, template, context)

yatube/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <meta charset="UTF-8">
    <title>
        {{ title }}
    </title>
</head>
<body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
            Контент
        {% endblock %}
    </main>
    <footer>
        {% include 'includes/footer.html' %}
    </footer>
</body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
    <p>© 2022 Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->

    {% load static %}

    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
                <span style="color:red">Ya</span>tube</a>

        </div>
    </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 style="margin-left: 80px; margin-top: 50px;">Лев Толстой – зеркало русской революции.</h1>
    <p  style="margin-left: 80px; margin-top: 10px;">Группа тайных поклонников графа.</p>
    {% for post in posts %}
        <div style="margin-left: 80px;">
            <ul>
                <li>
                    Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                    Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
            </ul>
            <p>
                {{ post.text }}
            </p>
            {% if not forloop.last %}
                <hr>
            {% endif %}
        </div>
    {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
    <h1 style="margin-left: 80px; margin-top: 50px;">Последние обновления на сайте</h1>
        {% for post in posts %}
            <div style="margin-left: 80px;">
                <ul>
                    <li>
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li>
                        Дата публикации: {{ post.pub_date|date:"d E Y" }}
                    </li>
                </ul>
                <p>{{ post.text }}</p>
                {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы {{ post.group }}</a>
                {% endif %}
                {% if not forloop.last %}
                    <hr>
                {% endif %}
            </div>
        {% endfor %}
{% endblock %}